[FIX] ADD minimal Sirius script for osx and linux
OpenMS/THIRDPARTY pull request #31
Opened 2017-10-06 10:48 UTC by oliveralka

Minimal script for execution of Sirius in the SiriusAdapter 

Tested:
1. Terminal (Sirius & SiriusAdapter)
2. KNIME 
OSX Sierra
Linux (lukas)

I had issues with it on the abinode - but it seemed that the issue was the same for CometAdapter - KNIME was not executing correctly. 
If you have time could you check if it is running for you on linux (if not we can always merge and see).

2017-10-09 14:20 UTC, lukaszimmermann requested changes

2017-10-09 14:20 UTC, lukaszimmermann commented on MacOS/64bit/Sirius/sirius
> +>>>>>>> 0bc31899568525f9edfb6d749650488bb96f05a2
Remainder from merging

2017-10-09 14:20 UTC, lukaszimmermann commented on MacOS/64bit/Sirius/sirius
> +wait
That is different from the Linux version. I guess the call here should be same for both OS.

2017-10-09 14:41 UTC, oliveralka commented
fix provided

2017-10-09 14:56 UTC, lukaszimmermann approved these changes

2017-10-09 14:57 UTC, merged

2017-10-22 11:46 UTC, hroest commented
@oliveralka can you add licence information to the script, e.g. the regular header that we also use for OpenMS?